ENV['AWS_ACCESS_KEY_ID'] = 'AKIAIHD7ZTEGBZZXCBKA'
ENV['AWS_SECRET_ACCESS_KEY'] = '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'
ENV['AWS-REGION'] = 'us-east-2'
ENV['PATH_STYLE'] = 'true'
ENV['S3_FILE'] = 'testfile2.txt'
ENV['bucket'] = 'minedmindskata'
